config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tours
  root 'tours#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
      if user.registered_user?
        can [:create, :update, :edit, :destroy], Tour, user_id: user.id
      else user.guest?
        can :read, :all
      end
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :tours
end

app/models/tour.rb
class Tour < ActiveRecord::Base
  belongs_to :category
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, presence: true
  enum role: [:guest, :registered_user]

  before_save :default_values

  def default_values
    self.role ||= 0
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  
      def configure_permitted_parameters
        devise_parameter_sanitizer.for(:sign_up) << :name
        devise_parameter_sanitizer.for(:account_update) << :name
      end

      rescue_from CanCan::AccessDenied do |exception|
      redirect_to root_url, alert: exception.message
      end

    
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  before_action :find_tour, only: [:show, :edit, :update, :destroy]
  before_action :check_moderator!, except: [:index, :show]

  def index

   if params[:category].blank?
      @tours = Tour.all.order("created_at DESC")
    else
      @category_id = Category.find_by(name: params[:category]).id
      @tours = Tour.where(category_id: @category_id).order("created_at DESC")
    end
  end

  def new
    @tour = Tour.new
  end

  def show
  end

  def create
    @tour = Tour.new(tours_params)

    if @tour.save
      redirect_to @tour
    else
      render "New"
    end
  end

  def edit
  end

  def update
    if @tour.update(tours_params)
      redirect_to @tour
    else
      render "Edit"
    end
  end

  def destroy
    @tour.destroy
    redirect_to root_path
  end

  private

  def tours_params
    params.require(:tour).permit(:tour, :place, :description, :price, :date, :duration, :reservations, :reviews, :category_id, :image)
  end

  def find_tour
    @tour = Tour.find(params[:id])  
  end

  def check_moderator!
    authenticate_user!
    unless current_user.registered_user?
      redirect_to root_path, alert: "You do not have access"
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tours_helper.rb
module ToursHelper
end

app/views/layouts/application.html.haml
!!!
%html
%head
	%title Tours4U 
	= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true 
	= javascript_include_tag 'application', 'data-turbolinks-track' => true 
	= csrf_meta_tags

%body
	%nav.navbar.navbar-default
		.container
			.navbar-brand TOURS4U
			%ul.nav.navbar-nav
				%li= link_to "All Tours", root_path
				- Category.all.each do |category|
					%li= link_to category.name, tours_path(category: category.name)
			
				-if user_signed_in? 
					= link_to "Log Out", destroy_user_session_path, method: :delete, class: "navbar-text navbar-right navbar-link"
				-else
					= link_to "Log In", new_user_session_path, class: "navbar-text navbar-right navbar-link"
					= link_to "Sign Up", new_user_registration_path, class: "navbar-text navbar-right navbar-link"
					
			
			= link_to "New Tour", new_tour_path, class: "navbar-text navbar-right navbar-link"
		


		.container
			.col-md-6.col-md-offset-3



				%p.notice= notice
				%p.alert= alert
				= yield

app/views/tours/_form.html.haml
= simple_form_for(@tour, html: { multipart: true, class: 'form-horizontal'}) do |f|
	= f.collection_select :category_id, Category.all, :id, :name, {promt: "Choose a category"}, input_html: { class: "dropdown-toggle" }
	= f.input :tour, label: "Tour Title", input_html: { class: "form-control"} 
	= f.input :place, label: "Place of Tour", input_html: { class: "form-control"} 
	= f.input_field :image, label: "Upload Picture", input_html: { class: "form-control"} 
	= f.input :description, label: "Tour Description", input_html: { class: "form-control"} 
	= f.input :price, label: "Price of Tour", input_html: { class: "form-control"} 
	= f.input :date, label: "Date of Tour", input_html: { class: "form-control"} 
	= f.input :duration, label: "Duration", input_html: { class: "form-control"} 
	= f.input :reservations, label: "Make a Resevation", input_html: { class: "form-control"} 
	= f.input :reviews, label: "Give us your opinion", input_html: { class: "form-control"} 
	%br/
	= f.button :submit


	

app/views/tours/edit.html.haml
%h1 Edit Tour

= render 'form'

= link_to "Back", root_path, class: "btn btn-sm btn-default"

app/views/tours/index.html.haml
#tours
	- @tours.each do |tour|
		.tour
			%h2= link_to tour.tour, tour
			%p= image_tag(tour.image, size:"370x300")
			%p= tour.place
			%p= tour.description

app/views/tours/new.html.haml
%h1 New Tour

= render 'form'

= link_to "Back", root_path, class: "btn btn-sm btn-default"

app/views/tours/show.html.haml
#tours
	.tour
		%h2= @tour.tour

		%p= @tour.place
		%p= @tour.description
		%p= @tour.price
		%p= @tour.date
		%p= @tour.duration
		%p= @tour.reservations
		%p= @tour.reviews
		
#links

	= link_to "Back", root_path, class: "btn btn-sm btn-default"
	= link_to "Edit", edit_tour_path(@tour) if can? :edit, Tour, class: "btn btn-sm btn-default"
	= link_to "Delete", tour_path(@tour), method: :delete, data: {confirm: "Are your sure?"} if can? :destroy, Tour, class: "btn btn-sm btn-default"